coverage:
  precision: 2
  round: nearest
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 100%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 100%
        base: auto
    changes: off
# The mock packages should not be included in code coverage
ignore:
    - "api/mock/.*"
