version: "2"
plugins:
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .jsx
  csslint:
    enabled: true
exclude_paths:
  - "bin/"
  - "coverage/"
  - "doc/"
  - "hooks/"
  - "lib/"
  - "src/**/*.test.jsx"
  - "src/**/*.test.js"
  - "src/config/locales/"
  - "*.json"
  - "**/*_test.go"
  - "**/vendor/"
  - "**/node_modules/"
  - "specs/"
  - "dist/"
  - "api/migrations/"
  - "api/templates/"
  - "api/testdata/"
