extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
env:
  browser: true
  es6: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - jsx-a11y
  - react
rules:
  # buggy
  jsx-a11y/label-has-for: 'off'

  # the following rules are disabled for legacy reasons, and most should be removed over time
  import/no-duplicates": 'off'
  jsx-a11y/anchor-is-valid: 'off'
  no-console: 'off'
  no-unused-vars: 'off'
  react/display-name: 'off'
  react/no-deprecated: 'off'
  react/no-string-refs: 'off'
  react/prop-types:
    - error
    - skipUndeclared: true
settings:
  import/resolver: webpack
