extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - airbnb
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  semi: ['error', 'never']
  no-console: 'warn'
  no-unused-vars: ['error', {
    argsIgnorePattern: '^_'
  }]
settings:
  import/resolver:
    babel-module:
      root: ['./src']
      alias:
        '@actions': './src/actions'
        '@components': './src/components'
        '@config': './src/config'
        '@constants': './src/constants'
        '@img': './src/img'
        '@plugins': './src/plugins'
        '@reducers': './src/reducers'
        '@schema': './src/schema'
        '@services': './src/services'
        '@validators': './src/validators'
        '@views': './src/views'
