extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - airbnb
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  semi: ['error', 'never']
  no-console: 'warn'
  no-unused-vars: ['error', {
    argsIgnorePattern: '^_'
  }]
settings:
  import/resolver:
    babel-module:
      root: ['./src']
