extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  # the following rules are disabled for legacy reasons, and most should be removed over time
  import/no-duplicates: 'off'
  import/namespace:
    - error
    - allowComputed: true
  no-console: 'off'
  no-unused-vars: 'off'
  react/no-deprecated: 'off'
  react/no-string-refs: 'off'
  react/display-name: 'off'
  react/prop-types:
    - error
    - skipUndeclared: true
  comma-dangle: ['error', { functions: 'never' }]
settings:
  import/resolver:
    babel-module:
      root: ['./src']
