extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  # the following rules are disabled for legacy reasons, and most should be removed over time
  import/no-duplicates: 'off'
  no-console: 'off'
  no-unused-vars: 'off'
  react/no-deprecated: 'off'
  react/no-string-refs: 'off'
  react/display-name: 'off'
  react/prop-types:
    - error
    - skipUndeclared: true
settings:
  import/resolver:
    babel-module:
      root: ['./src']
      alias:
        '@actions': './src/actions'
        '@components': './src/components'
        '@config': './src/config'
        '@img': './src/img'
        '@plugins': './src/plugins'
        '@reducers': './src/reducers'
        '@schema': './src/schema'
        '@services': './src/services'
        '@validators': './src/validators'
        '@views': './src/views'