extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - airbnb
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  semi: ['error', 'never']
  no-console: 'warn'
  no-unused-vars: ['error', {
    argsIgnorePattern: '^_'
  }]
  comma-dangle: [2, {
    arrays: 'always-multiline',
    objects: 'always-multiline',
    imports: 'always-multiline',
    exports: 'always-multiline',
    functions: 'ignore'
  }]
  react/forbid-prop-types: ['error', {
    forbid: ['any']
  }]
  react/jsx-boolean-value: ['error', 'always']
  jsx-a11y/label-has-for: 0
  jsx-a11y/label-has-associated-control: 2
settings:
  import/resolver:
    babel-module:
      root: ['./src']
  react:
    version: 'detect'