language: node

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - cp .env.test .env
  - docker-compose build
  - docker-compose run api ./test.sh
  - docker-compose run frontend npm test

after_success:
  - npm install -g codecov
  - codecov

after_script:
  - npm install -g pa11y-crawl
  - pa11y-crawl --run "docker-compose up" --ci http://localhost:8080

before_deploy:
  - ./bin/predeploy.sh

deploy:
  - provider: script
    script: "./bin/deploy.sh staging"
    skip_cleanup: true
    on:
      branch: pre-usability-fixes
      repo: truetandem/e-QIP-prototype
  - provider: script
    script: "./bin/deploy.sh production"
    skip_cleanup: true
    on:
      branch: master
      repo: 18F/e-QIP-prototype
