FROM scratch

# Run in a non-privilege user scope
COPY ./conf/passwd /etc/passwd
USER runner

# Certificates
COPY ./api/kx.crt /kx.crt
COPY ./api/eapp.crt /eapp.crt
COPY ./api/eapp.key /eapp.key

# Database migrations
COPY ./api/db /db

# Templates
COPY ./api/templates /templates

# Checksums
COPY ./api/checksum /checksum

# Third-party dependencies
COPY ./api/bin/xmlsec1 /bin/xmlsec1

COPY ./api/api /eapp-backend
ENTRYPOINT ["/eapp-backend"]
