FROM golang:1.10.0
RUN export DEBIAN_FRONTEND=noninteractive; apt-get -q -y update; apt-get -q -y install postgresql xmlsec1;
RUN go get github.com/derekparker/delve/cmd/dlv;
RUN go get -u github.com/Masterminds/glide; \
    cd $GOPATH/src/github.com/Masterminds/glide; \
    git checkout tags/$(git describe --tags $(git rev-list --tags --max-count=1)); \
    go install; \
    cd $GOPATH/src
