FROM golang:1.7
RUN go get -u github.com/Masterminds/glide; \
    cd $GOPATH/src/github.com/Masterminds/glide; \
    git checkout tags/$(git describe --tags $(git rev-list --tags --max-count=1)); \
    go install; \
    cd $GOPATH/src
