FROM scratch

# # Run in a non-privilege user scope
# COPY ./conf/passwd /etc/passwd
# COPY ./conf/group /etc/group
# USER runner

# Copy over pre-staged directory
COPY --chown=runner:runner ./api/dist/ /

# Set an entry point
ENTRYPOINT ["/eapp-backend"]
