# extends docker-compose.yml
# https://docs.docker.com/compose/extends/#multiple-compose-files

version: '2'

services:
  hub:
    image: selenium/hub:latest
    expose:
      - '4444'
    networks:
      - eapp

  # Selenium nodes currently don't support docker networks.
  # To get around this we emulate what `--link` would create for
  # environment variables.
  #
  # Reference: https://github.com/SeleniumHQ/docker-selenium/issues/133
  chrome:
    image: selenium/node-chrome:latest
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - eapp
    depends_on:
      - hub

  nightwatch:
    build:
      context: .
      dockerfile: conf/docker/Dockerfile.nightwatch
    command: [npm, run, docker]
    volumes:
      - ./specs:/usr/src/app
    networks:
      - eapp
    depends_on:
      - chrome
      - web
