export default {
  LOGIN_SUCCESS: 'AUTHENTICATION_LOGIN_SUCCESS',
  TWOFACTOR_QRCODE: 'AUTHENTICATION_TWOFACTOR_QRCODE',
  TWOFACTOR_SUCCESS: 'AUTHENTICATION_TWOFACTOR_SUCCESS',
  LOGOUT: 'AUTHENTICATION_LOGOUT'
}
