export default {
  LOGIN_SUCCESS: 'AUTHENTICATION_LOGIN_SUCCESS',
  LOGIN_ERROR: 'AUTHENTICATION_LOGIN_ERROR',
  TWOFACTOR_QRCODE: 'AUTHENTICATION_TWOFACTOR_QRCODE',
  TWOFACTOR_SUCCESS: 'AUTHENTICATION_TWOFACTOR_SUCCESS',
  TWOFACTOR_ERROR: 'AUTHENTICATION_TWOFACTOR_ERROR',
  LOGOUT: 'AUTHENTICATION_LOGOUT'
}
