package logmsg

// Warning messages
const (
	WarnFailedMigration      = "Failed to migrate database"
	MiddlewareError          = "Middleware has thrown an error"
	MFAAttemptDenied         = "An attempt for multiple factor authentication was denied"
	RetrievingAccount        = "Retrieving account"
	NoUsername               = "Unable to retrieve account because no username was provided"
	NoAccount                = "Unable to retrieve account"
	AccountUpdateError       = "Not ablet to update account information"
	NoAuthorizationToken     = "No authorization token header found"
	InvalidJWT               = "Invalid JSON web token"
	QRCodeError              = "Failed to generate multiple factor authentication QR code"
	MFAError                 = "Error during multiple factor authentication"
	MFAInvalid               = "Failed multiple factor authentication"
	MFAEmailError            = "Failed to send email for multiple factor authentication"
	MFAResetAttempt          = "An attempt to reset multiple factor authentication was denied"
	JWTError                 = "Failed to generate JSON web token"
	OAuthAttemptDenied       = "An attempt for OAuth authentication was denied"
	OAuthConfigurationError  = "Failed to create OAuth service bindings"
	OAuthStateError          = "Invalid OAuth state"
	OAuthCodeExchangeError   = "OAuth code exchange failed"
	BasicAuthAttemptDenied   = "An attempt for basic authentication was denied"
	BasicAuthError           = "Failed to decode JSON for basic authentication"
	BasicAuthMissingUsername = "Basic authentication failed because missing a username"
	BasicAuthMissingPassword = "Basic authentication failed because missing a password"
	BasicAuthInvalid         = "Basic authentication invalid"
	SamlAttemptDenied        = "An attempt for SAML authentication was denied"
	SamlRequestError         = "Error creating SAML authentication request"
	SamlRequestURLError      = "Error creating SAML authentication request URL"
	SamlFormError            = "SAML response form value missing"
	SamlParseError           = "Error parsing SAML response"
	SamlInvalid              = "SAML response invalid"
	SamlIdentifierMissing    = "SAML attribute identifier missing"
	PayloadMissingType       = "Payload is missing a type"
	PayloadEntityError       = "Error creating entity from the payload"
	EntityError              = "Error getting entity data"
	EntitySaveError          = "Error getting entity data"
	PayloadEmpty             = "Payload not provided"
	PayloadDeserializeError  = "Failed to deserialize payload"
	PayloadInvalid           = "Payload is invalid"
	USPSRequestError         = "Error executing USPS geocoding request"
	USPSDecodeError          = "Error decoding USPS geocoding response"
	USPSKnownErrorCode       = "USPS known error received"
	USPSUnknownErrorCode     = "USPS known error received"
	USPSMissingKey           = "USPS API key has not been set"
	MigrationUnsupported     = "Database migrations are not automated for Windows. Please manually execute the migrations."
)

// Informative messages
const (
	StartingServer     = "Starting server"
	ValidatingJWT      = "Validating JSON web token"
	GenerateQRCode     = "Generating multiple factor authentication QR code"
	ResetMFA           = "Reset of multiple factor authentication"
	OAuthConfiguration = "Configuring OAuth service"
	PurgeAccountData   = "Purging account data"
)
