/* eslint import/prefer-default-export: 0 */

export const VALIDATE_FORM_DATA = 'VALIDATE_FORM_DATA'
export const SET_FORM_DATA = 'SET_FORM_DATA'

export const UPDATE_SUBSECTION_DATA = 'UPDATE_SUBSECTION_DATA'
export const UPDATE_SUBSECTION_ERRORS = 'UPDATE_SUBSECTION_ERRORS'
export const UPDATE_SUBSECTION_COMPLETE = 'UPDATE_SUBSECTION_COMPLETE'
