export const SF85 = {
  HISTORY_RESIDENCE_YEARS: 5,
  HISTORY_EDUCATION_YEARS: 5,
  HISTORY_EMPLOYMENT_YEARS: 5,
}

export const SF85P = {
  HISTORY_RESIDENCE_YEARS: 7,
  HISTORY_EDUCATION_YEARS: 7,
  HISTORY_EMPLOYMENT_YEARS: 7,
}

export const SF86 = {
  HISTORY_RESIDENCE_YEARS: 10,
  HISTORY_EDUCATION_YEARS: 10,
  HISTORY_EMPLOYMENT_YEARS: 10,
}
