export const SF85 = {
  HISTORY_RESIDENCE_YEARS: 5,
  HISTORY_EDUCATION_YEARS: 5,
  HISTORY_EMPLOYMENT_YEARS: 5,
  HISTORY_EMPLOYMENT_RECORD_YEARS: 5,
  MILITARY_DISCIPLINARY_RECORD_YEARS: 5,
  FINANCIAL_RECORD_TAXES_YEARS: 5,
  FINANCIAL_RECORD_DELINQUENT_YEARS: 5,
  SUBSTANCE_DRUG_USE_YEARS: 1,
  SUBSTANCE_DRUG_TREATMENT_YEARS: 1,
  LEGAL_POLICE_RECORD_YEARS: 5,
  LEGAL_INVESTIGATED_YEARS: 'EVER',
  LEGAL_INVESTIGATED_DENIED_CLEARANCE_YEARS: 5,
  LEGAL_INVESTIGATED_DEBARRED_YEARS: 5,
  FORM_LABEL: 'SF-85'
}

export const SF85P = {
  HISTORY_RESIDENCE_YEARS: 7,
  HISTORY_EDUCATION_YEARS: 7,
  HISTORY_EMPLOYMENT_YEARS: 7,
  HISTORY_EMPLOYMENT_RECORD_YEARS: 7,
  FINANCIAL_RECORD_GAMBLING_YEARS: 7,
  FINANCIAL_RECORD_TAXES_YEARS: 7,
  FINANCIAL_RECORD_DELINQUENT_YEARS: 7,
  SUBSTANCE_DRUG_USE_YEARS: 7,
  SUBSTANCE_DRUG_TREATMENT_YEARS: 7,
  SUBSTANCE_ALCOHOL_TREATMENT_YEARS: 7,
  LEGAL_POLICE_RECORD_YEARS: 7,
  LEGAL_INVESTIGATED_YEARS: 'EVER',
  LEGAL_INVESTIGATED_DENIED_CLEARANCE_YEARS: 'EVER',
  LEGAL_INVESTIGATED_DEBARRED_YEARS: 'EVER',
  FORM_LABEL: 'SF-85P'
}

export const SF86 = {
  HISTORY_RESIDENCE_YEARS: 10,
  HISTORY_EDUCATION_YEARS: 10,
  HISTORY_EMPLOYMENT_YEARS: 10,
  HISTORY_EMPLOYMENT_RECORD_YEARS: 7,
  HISTORY_FEDERAL_YEARS: 10,
  MILITARY_DISCIPLINARY_RECORD_YEARS: 7,
  FINANCIAL_RECORD_TAXES_YEARS: 7,
  FINANCIAL_RECORD_DELINQUENT_YEARS: 7,
  FINANCIAL_RECORD_GAMBLING_YEARS: 'EVER',
  SUBSTANCE_DRUG_USE_YEARS: 7,
  SUBSTANCE_DRUG_TREATMENT_YEARS: 'EVER',
  SUBSTANCE_ALCOHOL_TREATMENT_YEARS: 'EVER',
  LEGAL_POLICE_RECORD_YEARS: 7,
  LEGAL_INVESTIGATED_YEARS: 'EVER',
  LEGAL_INVESTIGATED_DENIED_CLEARANCE_YEARS: 'EVER',
  LEGAL_INVESTIGATED_DEBARRED_YEARS: 'EVER',
  FORM_LABEL: 'SF-86'
}
