-- Sample Account Data
INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('admin', 'Sudo', 'McSudoson');

INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES (LASTVAL(), '$2a$10$s4IjNKAwwWSOJWMYRe5LK.ZRJr8pFRfIXtdJpQrJaYGjTKk/W6Kt6', CURRENT_TIMESTAMP);
