-- +goose Env GOLANG_ENV:development GOLANG_ENV:staging
-- +goose Up
-- SQL in section 'Up' is executed when this migration is applied
-- +goose StatementBegin
INSERT INTO ACCOUNTS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (DEFAULT, 'jun', 'Jun', 'Test');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'jun'), '$2a$10$H4yC7SNscjq349Vkkm7Cf.qUJ4am6zZJ2GNLBfhLyEj9FFyEJ61lq', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('prasad', 'Prasad', 'Test');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'prasad'), '$2a$10$H4yC7SNscjq349Vkkm7Cf.qUJ4am6zZJ2GNLBfhLyEj9FFyEJ61lq', CURRENT_TIMESTAMP);

-- +goose StatementEnd


-- +goose Down
-- SQL section 'Down' is executed when this migration is rolled back
-- +goose StatementBegin
DELETE FROM BASIC_AUTH_MEMBERSHIPS WHERE ACCOUNT_ID = (SELECT ID FROM ACCOUNTS WHERE USERNAME LIKE 'jun');
DELETE FROM ACCOUNTS WHERE USERNAME LIKE 'jun';

DELETE FROM BASIC_AUTH_MEMBERSHIPS WHERE ACCOUNT_ID = (SELECT ID FROM ACCOUNTS WHERE USERNAME LIKE 'prasad');
DELETE FROM ACCOUNTS WHERE USERNAME LIKE 'prasad';
-- +goose StatementEnd
