-- +goose Env GOLANG_ENV:development GOLANG_ENV:staging
-- +goose Up
-- SQL in section 'Up' is executed when this migration is applied
-- +goose StatementBegin
INSERT INTO ACCOUNTS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (DEFAULT, 'test01', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test01'), '$2a$10$NOHK.2LsTVVxjNDzo6Dqd.l/c9vEYNH.JmdxjnxjvDN9Q4XzRx4QG', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test02', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test02'), '$2a$10$KmM8DM61HEFBrzHB/eyLyOA/SJH.nxFs635P6mUOuOr9QuV5IiCVq', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test03', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test03'), '$2a$10$LeaIH5fNq1eq8.Eya9e4HuZSRv4ZqMSX3QLzj9FKdPaDpHf686/Gy', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test04', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test04'), '$2a$10$rCCa4xfbtxB/BvX/hq5ghulSbQvJmemmz0ITjzZQi2MYGjuovOuvK', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test05', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test05'), '$2a$10$4iMmtj56bbNumPqlK1Y3Xu18U7/kPLgWDcIBPc.tdpvO52FX9Ax3q', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test06', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test06'), '$2a$10$ieNcR87dPhRxkKJdgpvxbuEgtmcVKGyrUeXyS5q69KL66EOlC5LzS', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test07', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test07'), '$2a$10$FPKiU4dy.H/7eT./KHQ.Euy705UNDNP8lSP4pHTG9xo2nBLcgvgWe', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test08', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test08'), '$2a$10$0P8ec64xqFRQqeG.fpcMe.hLD1nNvGsWdZR4wzcbP.j9eOqFLrJp2', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test09', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test09'), '$2a$10$DQKwTq296jmp6rfACHHVa.vuCbCo6Kh9xCYT.ATtyvuoFCs5GIJpa', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test10', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test10'), '$2a$10$Jpy4iJKUUas8DkKfujKucuGKolYvEHxAdhRVtA4jeeVQ0o3DvzhE2', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test11', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test11'), '$2a$10$034ASuUgMUOCe5z7rZc1muyG2TIIO9jqwKKaOvr6sCIzCQLlF6b02', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test12', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test12'), '$2a$10$2tsrnREWS68WkdqC8Z4riOab.is7I4Bkz8xsVCa6vN1hyl4ZzLvPi', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test13', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test13'), '$2a$10$0BsZQZmMn8XvJtytvuKlXO.lkU3KBf0l/8vnjsi3fcmu5v2l8lVmG', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test14', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test14'), '$2a$10$sjBr9U.KWU5ui7fxYX.uOeF03RwZGe4UVRltqM9Rjy73qE5I88PwW', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test15', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test15'), '$2a$10$l4aYmlM7nXS17UdPHwIXpuGtHyJ4QuPmIAStceRHgIPTHsQ1SMTCW', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test16', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test16'), '$2a$10$NPsdiB5H6UGFnaVX443aOO8ZZA5jD.XhLH3oMcFHNytS8x6wjyqEm', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test17', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test17'), '$2a$10$RkbQokkMeduSnYB.WXvIIenmMBcAA3THrG949UQvc1Zg1/zh96HDS', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test18', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test18'), '$2a$10$H7k.TkxLKfMnr8SxwZbuQe6vc0JGt/8CCNnNRP4deNKth5kWJuIne', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test19', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test19'), '$2a$10$DUv7uJdLry1Wo2txV7r.8OQHwzKtYNAZYRJ.0/59Qeab7DJ0w9YM2', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNTS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('test20', 'Test', 'Account');
INSERT INTO BASIC_AUTH_MEMBERSHIPS (ACCOUNT_ID, PASSWORD_HASH, CREATED) VALUES ((SELECT ID FROM ACCOUNTS WHERE USERNAME = 'test20'), '$2a$10$E6ZuHetJGDnMfGdhg8h0NO3.8MmvTmw3H6TYfHo17yqRuviMnnLMq', CURRENT_TIMESTAMP);
-- +goose StatementEnd


-- +goose Down
-- SQL section 'Down' is executed when this migration is rolled back
-- +goose StatementBegin
DELETE FROM BASIC_AUTH_MEMBERSHIPS WHERE ACCOUNT_ID = (SELECT ID FROM ACCOUNTS WHERE USERNAME LIKE 'test%');
DELETE FROM ACCOUNTS WHERE USERNAME LIKE 'test%';
-- +goose StatementEnd
